#!/usr/bin/env bash
set -euo pipefail

umask 077

OUTPUT_FILE="${1:-.env}"
TEMP_FILE=""

fail() {
  printf 'Σφάλμα: %s\n' "$*" >&2
  exit 1
}

cleanup() {
  if [[ -n "$TEMP_FILE" ]]; then
    rm -f -- "$TEMP_FILE"
  fi
}
trap cleanup EXIT

prompt_with_default() {
  local variable_name="$1"
  local label="$2"
  local default_value="$3"
  local allowed_pattern="$4"
  local value

  while true; do
    read -r -p "$label [$default_value]: " value || fail "Η είσοδος διακόπηκε."
    value="${value:-$default_value}"

    if [[ "$value" =~ $allowed_pattern ]]; then
      printf -v "$variable_name" '%s' "$value"
      return
    fi

    printf 'Μη έγκυρη τιμή. Επιτρεπτοί χαρακτήρες: γράμματα, αριθμοί, τελεία, παύλα, κάτω παύλα, κάθετος και άνω-κάτω τελεία.\n' >&2
  done
}

prompt_openrouter_key() {
  local value

  while true; do
    if [[ -t 0 ]]; then
      read -r -s -p 'OpenRouter API key: ' value || fail "Η είσοδος διακόπηκε."
      printf '\n' >&2
    else
      read -r value || fail "Δεν δόθηκε OpenRouter API key."
    fi

    if [[ "$value" =~ ^sk-or-[A-Za-z0-9._-]+$ ]]; then
      OPENROUTER_API_KEY="$value"
      return
    fi

    printf 'Το OpenRouter API key πρέπει να είναι μη κενό και να αρχίζει με sk-or-.\n' >&2
  done
}

random_hex() {
  openssl rand -hex 32
}

command -v openssl >/dev/null 2>&1 || fail "Απαιτείται το openssl."

if [[ -e "$OUTPUT_FILE" ]]; then
  if [[ ! -t 0 ]]; then
    fail "Το $OUTPUT_FILE υπάρχει ήδη. Η μη διαδραστική εκτέλεση δεν το αντικαθιστά."
  fi

  read -r -p "Το $OUTPUT_FILE υπάρχει ήδη. Να αντικατασταθεί; [y/N]: " overwrite
  case "$overwrite" in
    y|Y|yes|YES)
      ;;
    *)
      printf 'Δεν έγινε καμία αλλαγή.\n'
      exit 0
      ;;
  esac
fi

output_directory="${OUTPUT_FILE%/*}"
if [[ "$output_directory" == "$OUTPUT_FILE" ]]; then
  output_directory='.'
fi
[[ -d "$output_directory" ]] || fail "Ο κατάλογος $output_directory δεν υπάρχει."

printf 'Δώστε τις τιμές που εξαρτώνται από το deployment. Πατήστε Enter για την προτεινόμενη τιμή.\n'

prompt_with_default HINDSIGHT_VERSION 'Hindsight image version' 'latest' '^[A-Za-z0-9][A-Za-z0-9._-]*$'
prompt_with_default LITELLM_VERSION 'LiteLLM image version' 'latest' '^[A-Za-z0-9][A-Za-z0-9._-]*$'
prompt_openrouter_key
prompt_with_default OPENROUTER_MODEL 'OpenRouter chat model' 'z-ai/glm-5.3-flash' '^[A-Za-z0-9][A-Za-z0-9._/:+-]*$'
prompt_with_default OPENROUTER_EMBEDDING_MODEL 'OpenRouter embedding model' 'perplexity/pplx-embed-v1-0.6b' '^[A-Za-z0-9][A-Za-z0-9._/:+-]*$'
prompt_with_default OPENROUTER_RERANKER_MODEL 'OpenRouter reranker model' 'cohere/rerank-v3.5' '^[A-Za-z0-9][A-Za-z0-9._/:+-]*$'

POSTGRES_PASSWORD="$(random_hex)"
LITELLM_MASTER_KEY="sk-$(random_hex)"
LITELLM_SALT_KEY="sk-$(random_hex)"
LITELLM_DB_PASSWORD="$(random_hex)"
HINDSIGHT_API_KEY="$(random_hex)"
HINDSIGHT_MCP_TOKEN="$(random_hex)"
HINDSIGHT_UI_ACCESS_KEY="$(random_hex)"

TEMP_FILE="$(mktemp "${OUTPUT_FILE}.tmp.XXXXXX")"
chmod 600 "$TEMP_FILE"

cat >"$TEMP_FILE" <<EOF
# Generated by generate-env.sh. Keep this file outside Git.

# -------------------------
# Hindsight
# -------------------------
HINDSIGHT_VERSION=$HINDSIGHT_VERSION

# OpenRouter
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
OPENROUTER_MODEL=$OPENROUTER_MODEL
OPENROUTER_EMBEDDING_MODEL=$OPENROUTER_EMBEDDING_MODEL
OPENROUTER_RERANKER_MODEL=$OPENROUTER_RERANKER_MODEL

# -------------------------
# Shared PostgreSQL instance
# -------------------------
POSTGRES_USER=hindsight
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=hindsight

# -------------------------
# LiteLLM
# -------------------------
LITELLM_VERSION=$LITELLM_VERSION
LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY
# Keep this value stable after the first deployment.
LITELLM_SALT_KEY=$LITELLM_SALT_KEY
LITELLM_DB_USER=litellm
LITELLM_DB_PASSWORD=$LITELLM_DB_PASSWORD
LITELLM_DB_NAME=litellm

# -------------------------
# Hindsight authentication
# -------------------------
HINDSIGHT_API_KEY=$HINDSIGHT_API_KEY
HINDSIGHT_MCP_TOKEN=$HINDSIGHT_MCP_TOKEN
HINDSIGHT_UI_ACCESS_KEY=$HINDSIGHT_UI_ACCESS_KEY
EOF

mv -f -- "$TEMP_FILE" "$OUTPUT_FILE"
TEMP_FILE=""

printf 'Δημιουργήθηκε το %s με permissions 600.\n' "$OUTPUT_FILE"
printf 'Τα τοπικά passwords και tokens δημιουργήθηκαν αυτόματα και δεν εμφανίστηκαν στο terminal.\n'
